on 'develop' => sub {
    requires 'Minilla', 'v3.1.19';
};

on 'test' => sub {
	requires 'Liveman', 
		git => 'https://github.com/darviarush/perl-liveman.git',
		ref => 'master',
	;
};

requires 'common::sense', '3.75';
requires 'Aion::View',
    git => 'https://github.com/darviarush/perl-aion-view.git',
    ref => 'master';
