services:
  {{name}}.admin.{{name}}:
    class: Restoclub\{{Name}}Bundle\Admin\{{Name}}Admin
    arguments: [ ~, Restoclub\{{Name}}Bundle\Entity\{{Name}}, {{Name}}Bundle:{{Name}}Admin]
    calls:
      - [ setTemplate, [list, {{Name}}Bundle:{{Name}}Admin:list.html.twig]]
    tags:
      - name: sonata.admin
        manager_type: orm
        label: Новый сервис
